version: '3'
services:  
  laravel:
    tty: true
    image: bitnami/laravel:7
    container_name: laravel_container
    ports:
      - 8083:3000
    volumes:
      - ./laravel:/app
    command: >
      bash -c " composer install
      && php artisan route:list
      && php artisan key:generate
      && php artisan migrate
      && php artisan db:seed
      && php artisan serve --host=0.0.0.0 --port=3000 "
    depends_on:
      - mysql
    networks:
      - servidor_network

  # go:
  #   image: golang:1.15
  #   container_name: go_container
  #   working_dir: /go/src/goApp
  #   volumes:
  #     - ./go:/go/src/goApp
  #   command: >
  #     bash -c " rm -f go.mod || true
  #     && rm -f go.sum || true
  #     && go mod init goApp
  #     && go mod tidy
  #     && go get github.com/jinzhu/gorm
  #     && go get github.com/pilu/fresh
  #     && fresh "
      
  #   ports:
  #     - "3000:3000"
  #   labels:
  #     traefik.backend: "web"
  #     traefik.frontend.rule: "PathPrefix:/"
  #   depends_on:
  #     - mysql
  #     - redis
  #   networks:
  #     - servidor_network

  discotecas:
    image: golang:1.15
    container_name: go_discotecas
    working_dir: /go/src/goApp_discotecas
    volumes:
      - ./go/discotecas:/go/src/goApp_discotecas
    command: >
      bash -c " rm -f go.mod || true
      && rm -f go.sum || true
      && go mod init goApp_discotecas
      && go mod tidy
      && go get github.com/jinzhu/gorm
      && go get github.com/pilu/fresh
      && fresh "
      
    ports:
      - "3000:8080"
    labels:
      traefik.backend: "web"
      traefik.frontend.rule: "PathPrefix:/"
    depends_on:
      - mysql
      - redis
      - traefik
    networks:
      - servidor_network

  users:
    image: golang:1.15
    container_name: go_users
    working_dir: /go/src/goApp_users
    volumes:
      - ./go/users:/go/src/goApp_users
    command: >
      bash -c " rm -f go.mod || true
      && rm -f go.sum || true
      && go mod init goApp_users
      && go mod tidy
      && go get github.com/jinzhu/gorm
      && go get github.com/pilu/fresh
      && fresh "
      
    ports:
      - "3001:8080"
    labels:
      traefik.backend: "web"
      traefik.frontend.rule: "PathPrefix:/"
    depends_on:
      - mysql
      - redis
      - traefik
    networks:
      - servidor_network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=gran_melon
      - MYSQL_USER=xema
      - MYSQL_PASSWORD=123456789
    volumes:
      - ./mySqlBackup:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - servidor_network

  redis:
    image: redis:4.0
    container_name: redis_container
    volumes:
      - ./redisData:/data
    ports:
      - "6382:6379"
    networks:
      - servidor_network

  #  traefik:
  #   image: traefik:v2.0
  #   container_name: traefik
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   networks:
  #     - proxy
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./data/traefik.yml:/traefik.yml:ro
  #     - ./data/acme.json:/acme.json
  #   labels:
  #     - "traefik.enable=true"
  #     # - "traefik.http.routers.traefik.entrypoints=http"
  #     - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
  #     - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
  #     - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
  #     - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
  #     - "traefik.http.routers.traefik-secure.entrypoints=https"
  #     - "traefik.http.routers.traefik-secure.rule=Host(`traefik.example.com`)"
  #     - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
  #     - "traefik.http.routers.traefik-secure.tls=true"
  #     - "traefik.http.routers.traefik-secure.tls.certresolver=http"
  #     - "traefik.http.routers.traefik-secure.service=api@internal"

  traefik:
    image: traefik:v1.7
    command: --docker --docker.domain=great_melon.io

    ports:
      - 8080:8080
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.great_melon.io"
      - "traefik.port=8080"
      - "traefik.http.routers.traefik.entrypoints=http"
    container_name: traefik
    restart: always

      
networks:
  servidor_network:
  proxy:
    external: true


###############  POSTGRESQL  ###############

  # postgresql:
  #   image: 'docker.io/bitnami/postgresql:13-debian-10'
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - 'postgresql_data:/bitnami/postgresql'
  #   environment:
  #     - 'ALLOW_EMPTY_PASSWORD=yes'
  #     - 'POSTGRES_PASSWORD=123456789'

    # networks: 
    #   - network

  # Esto es como el phpmyadmin 
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "elgran@melon.es"
#       PGADMIN_DEFAULT_PASSWORD: "@Melon"
#     ports:
#       - 6969:80
#     networks: 
#       - network
# volumes:
#   postgresql_data:



###############  COPIA  ###############
# version: "3"
# services:
#   laravel:
#     tty: true
#     image: bitnami/laravel:7
#     container_name: laravel_container
#     ports:
#       - 8083:3000
#     volumes:
#       - ./laravel:/app
#     command: >
#       bash -c " composer install
#       && php artisan route:list
#       && php artisan key:generate
#       && php artisan migrate
#       && php artisan db:seed
#       && php artisan serve --host=0.0.0.0 --port=3000 "
#     depends_on:
#       - database
#       - redis
#     networks:
#       - servidor_network

#   web:
#     image: golang:1.15
#     container_name: go_container
#     working_dir: /go/src/goApp
#     volumes:
#       - ./go:/go/src/goApp
#     command: >
#       bash -c " rm -f go.mod || true
#       && rm -f go.sum || true
#       && go mod init goApp
#       && go mod tidy
#       && go get github.com/pilu/fresh
#       && fresh "
#     ports:
#       - "8090:3000"
#     labels:
#       traefik.backend: "web"
#       traefik.frontend.rule: "PathPrefix:/"
#     depends_on:
#       - database
#       - redis
#     networks:
#       - servidor_network

#   database:
#     image: mysql:5.7
#     container_name: database_container
#     environment:
#       - "MYSQL_DATABASE=laravel"
#       - "MYSQL_ROOT_PASSWORD=common404"
#     volumes:
#       - ./mySqlBackup:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     networks:
#       - servidor_network

#   redis:
#     image: redis:4.0
#     container_name: redis_container
#     volumes:
#       - redisData:/data
#     ports:
#       - "6382:6379"
#     networks:
#       - servidor_network

#   traefik:
#     image: traefik:v2.0
#     container_name: traefik_container
#     ports:
#       - "80:80"
#       - "8080:8080"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./traefik/traefik.yml:/etc/traefik/traefik.yml
#     networks:
#       - servidor_network

# networks:
#   servidor_network:

# volumes:
#   redisData: