version: '3'
services:  
  laravel:  #NO
    tty: true 
    image: bitnami/postgresql:latest
    environment:
      - DB_HOST=127.0.0.1
      - DB_CONNECTION=pgsql
      - DB_USERNAME=elgranmelon
      - DB_DATABASE=db_elgranmelon
      - DB_PASSWORD=postgres123@?
      - DB_PORT=5432
      - POSTGRESQL_PASSWORD=''
    depends_on:
      - postgresql
    # command: 
    #    php artisan serve --port=3000
    ports:
      - 3100:3000
    volumes:
      - ./laravel:/app
    # networks: 
    #   - network tonto: DALEEEEEEEEEEEEEEEEEEEEEEE xema: QUE NO VAAAAA
      
  postgresql:
    image: 'docker.io/bitnami/postgresql:13-debian-10'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      # - 'POSTGRES_PASSWORD=123456789'
      
 #cierralo a ver

    # networks: 
    #   - network

  # Esto es como el phpmyadmin 
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "elgran@melon.es"
#       PGADMIN_DEFAULT_PASSWORD: "@Melon"
#     ports:
#       - 6969:80
#     networks: 
#       - network

# networks: 
#   network:
#     external: true

volumes:
  postgresql_data:

    #TONO, si le pones una network external, la busca en alguna que ya está creada, pero como no está creada peta y por eso tienes que crearla tu a mano



#A ver, vamos a organizar aqui lo que necesitamos:
# Servicios totales: laravel, postgres,
#
#
#
#
#
#
#

# services:

#   nginx:
#     image: nginx:latest
#     ports:
#       - 8083:80
#     volumes:
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     volumes_from:
#       - php

#   php:
#     build: ./docker/php/
#     volumes:
#       - .:/var/www/html
#       - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
#     links:
#         - database
#         - redis
#     environment:
#       - "DB_PORT=3306"
#       - "DB_HOST=database"

#   database:
#         image: mysql:5.7
#         environment:
#           - "MYSQL_DATABASE=laravel"
#           - "MYSQL_ROOT_PASSWORD=common404"
#         volumes:
#           - ${BACKUP_DATA_PATH}/mysql3:/var/lib/mysql
#         ports:
#           - "3306:3306"

#   redis:
#         image: redis:4.0
#         ports:
#           - "6382:6379"
