version: '3'
services:  
  laravel:
    tty: true
    image: bitnami/laravel:7
    container_name: laravel_container
    ports:
      - 8000:3000
    volumes:
      - ./laravel:/app
    command: >
      bash -c " composer install
      && php artisan route:list
      && php artisan key:generate
      && php artisan migrate
      && php artisan db:seed
      && php artisan serve --host=0.0.0.0 --port=3000"
    depends_on:
      - mysql
    networks:
      - servidor_network

  # go:
  #   image: golang:1.15
  #   container_name: go_container
  #   working_dir: /go/src/goApp
  #   volumes:
  #     - ./go:/go/src/goApp
  #   command: >
  #     bash -c " rm -f go.mod || true
  #     && rm -f go.sum || true
  #     && go mod init goApp
  #     && go mod tidy
  #     && go get github.com/jinzhu/gorm
  #     && go get github.com/pilu/fresh
  #     && fresh "
      
  #   ports:
  #     - "3000:3000"
  #   labels:
  #     traefik.backend: "web"
  #     traefik.frontend.rule: "PathPrefix:/"
  #   depends_on:
  #     - mysql
  #     - redis
  #   networks:
  #     - servidor_network

  discotecas:
    image: golang:1.15
    container_name: go_discotecas
    working_dir: /go/src/goApp_discotecas
    volumes:
      - ./go/discotecas:/go/src/goApp_discotecas
    command: >
      bash -c " rm -f go.mod || true
      && rm -f go.sum || true
      && go mod init goApp_discotecas
      && go mod tidy
      && go get github.com/jinzhu/gorm
      && go get github.com/pilu/fresh
      && fresh "

    expose:
    - 8080
    labels:
      traefik.http.routers.discotecas.rule: Host(`discotecas.docker.localhost`)
      traefik.enable: true
      traefik.docker.network: servidor_network
      traefik.port: 8080
    depends_on:
      - mysql
      - redis
    networks:
      - servidor_network

  users:
    image: golang:1.15
    container_name: go_users
    working_dir: /go/src/goApp_users
    volumes:
      - ./go/users:/go/src/goApp_users
    command: >
      bash -c " rm -f go.mod || true
      && rm -f go.sum || true
      && go mod init goApp_users
      && go mod tidy
      && go get github.com/jinzhu/gorm
      && go get github.com/pilu/fresh
      && fresh "
    expose:
    - 8080
    labels:
      traefik.http.routers.users.rule: Host(`users.docker.localhost`)
      traefik.enable: true
      traefik.docker.network: servidor_network
      traefik.port: 8080
    depends_on:
      - mysql
      - redis
    networks:
      - servidor_network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=gran_melon
      - MYSQL_USER=xema
      - MYSQL_PASSWORD=123456789
    volumes:
      - ./mySqlBackup:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - servidor_network

  redis:
    image: redis:4.0
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - ./redisData:/data
    networks:
      - servidor_network

  traefik:
    image: traefik:v2.3
    command: --api.dashboard=true --api.insecure=true --providers.docker --entrypoints.web.address=:80

    ports:
      - 80:80
      - 8080:8080
    networks:
      - servidor_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - "traefik.port=8080"
    container_name: traefik
    depends_on: 
    - users
    restart: always

  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - "3500:3000"
    volumes:
      - './common/grafana:/etc/grafana/provisioning/datasources/'
      - 'grafana:/var/lib/grafana'
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel 1.0.1"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    depends_on: 
      - users
      - laravel
    networks:
      - servidor_network

networks:
  servidor_network:

volumes:
  grafana:

# [17:27, 2/1/2021] Joel - Instalation: tu tens que fer que tots els microserveis ixquen per el 80 si no m'equivoque
# [17:27, 2/1/2021] Joel - Instalation: i en el main.go igual
# [17:27, 2/1/2021] tonomolla6: pero, per el mateix?
# [17:27, 2/1/2021] tonomolla6: Y com faig les peticions
# [17:27, 2/1/2021] Joel - Instalation: i traefik ja els distribueix
# [17:27, 2/1/2021] Joel - Instalation: go_users.docker.localhost o algo aixina
# [17:27, 2/1/2021] tonomolla6: Vale
# [17:27, 2/1/2021] Joel - Instalation: sense indicar port

###############  POSTGRESQL  ###############

  # postgresql:
  #   image: 'docker.io/bitnami/postgresql:13-debian-10'
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - 'postgresql_data:/bitnami/postgresql'
  #   environment:
  #     - 'ALLOW_EMPTY_PASSWORD=yes'
  #     - 'POSTGRES_PASSWORD=123456789'

    # networks: 
    #   - network

  # Esto es como el phpmyadmin 
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "elgran@melon.es"
#       PGADMIN_DEFAULT_PASSWORD: "@Melon"
#     ports:
#       - 6969:80
#     networks: 
#       - network
# volumes:
#   postgresql_data:



###############  COPIA  ###############
# version: "3"
# services:
#   laravel:
#     tty: true
#     image: bitnami/laravel:7
#     container_name: laravel_container
#     ports:
#       - 8083:3000
#     volumes:
#       - ./laravel:/app
#     command: >
#       bash -c " composer install
#       && php artisan route:list
#       && php artisan key:generate
#       && php artisan migrate
#       && php artisan db:seed
#       && php artisan serve --host=0.0.0.0 --port=3000 "
#     depends_on:
#       - database
#       - redis
#     networks:
#       - servidor_network

#   web:
#     image: golang:1.15
#     container_name: go_container
#     working_dir: /go/src/goApp
#     volumes:
#       - ./go:/go/src/goApp
#     command: >
#       bash -c " rm -f go.mod || true
#       && rm -f go.sum || true
#       && go mod init goApp
#       && go mod tidy
#       && go get github.com/pilu/fresh
#       && fresh "
#     ports:
#       - "8090:3000"
#     labels:
#       traefik.backend: "web"
#       traefik.frontend.rule: "PathPrefix:/"
#     depends_on:
#       - database
#       - redis
#     networks:
#       - servidor_network

#   database:
#     image: mysql:5.7
#     container_name: database_container
#     environment:
#       - "MYSQL_DATABASE=laravel"
#       - "MYSQL_ROOT_PASSWORD=common404"
#     volumes:
#       - ./mySqlBackup:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     networks:
#       - servidor_network

#   redis:
#     image: redis:4.0
#     container_name: redis_container
#     volumes:
#       - redisData:/data
#     ports:
#       - "6382:6379"
#     networks:
#       - servidor_network

#   traefik:
#     image: traefik:v2.0
#     container_name: traefik_container
#     ports:
#       - "80:80"
#       - "8080:8080"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./traefik/traefik.yml:/etc/traefik/traefik.yml
#     networks:
#       - servidor_network

# networks:
#   servidor_network:

# volumes:
#   redisData: